backend:
  name: github
  repo: r00bal/Gatsby-portfolio-starter
  # branch: master Branch to update (optional; defaults to master)

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: projects
    label: Projects
    editor:
      preview: true
    slug: '{{path}}'
    folder: 'src/assets/projects'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: slug, label: Slug }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - {
          label: 'Project Images',
          name: 'projectImages',
          widget: 'list',
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Text, name: text, widget: text },
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
