backend:
  name: github
  repo: r00bal/Gatsby-portfolio-starter
  branch: test-cms

media_folder: static/images
public_folder: /images

collections:
  - name: projects
    label: Projects
    editor:
      preview: true
    slug: '{{slug}}'
    folder: 'src/assets/projects'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { name: slug, label: Slug }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'FrontImage', name: 'frontImage', widget: 'image' }
      - {
          label: 'Projects',
          name: 'projects',
          widget: 'list',
          fields:
            [
              { label: Alt, name: alt, widget: text },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: text },
              { label: Image, name: image, widget: image },
            ],
        }

      - { label: 'Body', name: 'body', widget: 'markdown' }
